### ISSUE TITLE
404 for userguide/find-resources-to-tag.html

### ISSUE THREAD

**Issue by scharlottej13** [awsdocs/aws-resource-groups-user-guide#8]
I'm currently getting a 404 for https://docs.aws.amazon.com/ARG/latest/userguide/find-resources-to-tag.html. Has this link been changed? I noticed the [corresponding markdown](https://github.com/awsdocs/aws-resource-groups-user-guide/blob/main/doc_source/find-resources-to-tag.md) is still in this repo. We reference this page in our docs.

Thanks in advance for your help!

**Comment by bisdavid** [comment]
Ouch.  I made a mistake publishing, and some redirects got put in place that shouldn’t have been.   I’m fixing this now, and the fixes should be live in about 2 hours or so.

Thanks for reporting this!
-------------------------------
davebishop
***@***.***


From: Sarah Charlotte Johnson ***@***.***>
Sent: Friday, December 2, 2022 12:07 PM
To: awsdocs/aws-resource-groups-user-guide ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [awsdocs/aws-resource-groups-user-guide] 404 for userguide/find-resources-to-tag.html (Issue #8)


I'm currently getting a 404 for https://docs.aws.amazon.com/ARG/latest/userguide/find-resources-to-tag.html. Has this link been changed? I noticed the corresponding markdown<https://github.com/awsdocs/aws-resource-groups-user-guide/blob/main/doc_source/find-resources-to-tag.md> is still in this repo. We reference this page in our docs.

Thanks in advance for your help!

**Comment by scharlottej13** [comment]
Great, thanks @bisdavid! Very much appreciate your quick reply!

**Comment by bisdavid** [comment]
And the Tag Editor section of the guide is back again.  Thanks again for reporting the issue to me, Sarah!
-------------------------------
davebishop

**Comment by scharlottej13** [comment]
Thanks @bisdavid!
